### ISSUE TITLE
lesson contributor count includes contributors to template

### ISSUE THREAD

**Issue by maneesha** [carpentries/feeds.carpentries.org#24]
The lesson contributor count ([script](https://github.com/carpentries/amy-feeds/blob/master/python/lesson_contributor_count.py) and [feed](https://feeds.carpentries.org/lesson_contributor_count.json)) includes contributors to the lesson template.

@ErinBecker  said @fmichonneau  may have suggestions on how to fix this to be a more accurate reflection of contributions.   François - no need to edit my code; just let me know how you may want to filter for lesson contributors.  Could we filter for contributions after a certain date?

**Comment by maneesha** [comment]
@zkamvar  I think this should resolve itself after the new lesson infrastructure is fully rolled out.  Is that right?

**Comment by zkamvar** [comment]
Yes, this should resolve itself in May.

**Comment by maneesha** [comment]
@zkamvar Is there anything we need to do for the lesson contributor count feeds now?

**Comment by maneesha** [comment]
checking in @zkamvar - if the answer to this is more than you can answer in a day, then we will figure it out later.

**Comment by zkamvar** [comment]
No there is nothing that needs to be done. The contributor counts should be mostly accurate. A few of the LC contributor counts are borked, but that's because of anomalous historical factors that I had not accounted for.
