### ISSUE TITLE
Minor errors should not prevent building of the feeds

### ISSUE THREAD

**Issue by zkamvar** [carpentries/feeds.carpentries.org#61]
The feeds build failed because one repository in the incubator was missing a GitHub description.

IMO, this is a thing that should indeed trigger an error on healthchecks, but the feeds should still be built. I think if we replaced the `stop()` command here with a GitHub error string `:: error::{message}`, then we would be able to get HelathChecks to error, but the feeds would still be built, albeit with missing information.

https://github.com/carpentries/feeds.carpentries.org/blob/8189a9aab38d8e4689c706263189f02f849d854a/R/community_lessons.R#L25-L41

**Comment by maneesha** [comment]
I will defer to @zkamvar  on this since it is about curriculum feeds and because he knows R **way** better than me.  Zhian, do you want to put in a PR?

**Comment by zkamvar** [comment]
I can certainly try!
