### ISSUE TITLE
Error in incubator feed

### ISSUE THREAD

**Issue by maneesha** [carpentries/feeds.carpentries.org#71]
The [incubator feed is failing](https://github.com/carpentries/feeds.carpentries.org/actions/runs/3529624065/jobs/5920799945#step:18:163) and this failure holds back the whole data feeds build.  I've [temporarily removed that make command](https://github.com/carpentries/feeds.carpentries.org/pull/70).  According to @tobyhodges [in Slack](https://swcarpentry.slack.com/archives/G0HP41W1Y/p1669118981199619) (private link):  

> I think I found and fixed the problem. Someone had added another life cycle stage tag to their lesson repository in the Incubator, but had not removed the old stage tag, and the script was failing because two different life cycle stages were present and it didn’t know how to deal with that. If I can figure out how to edit the script, I will open a PR to update it so that the later life cycle stage is chosen in cases like this (i.e. stable>beta>alpha>pre-alpha)

This is [script that builds the incubator feed](https://github.com/carpentries/feeds.carpentries.org/blob/main/R/community_lessons.R).  I think we should be able to edit this to choose just one tag but my R skills are not so good so I will leave it to someone who is better at this.

**Comment by maneesha** [comment]
Once that script is fixed, that line should be added back to the Makefil.

**Comment by zkamvar** [comment]
Note for posterity (because the logs only survive for 90 days at most), here is the error:

```
Error in `dplyr::mutate()`:
! Problem while computing `life_cycle_tag = purrr::pmap(...)`.
Caused by error in `.f()`:
! More than one tag detected for: carpentries-incubator/lesson-parallel-python
Backtrace:
     ▆
  1. ├─base::source("R/community_lessons.R")
  2. │ ├─base::withVisible(eval(ei, envir))
  3. │ └─base::eval(ei, envir)
  4. │   └─base::eval(ei, envir)
  5. ├─global make_community_lessons_feed("_data/community_lessons.json")
  6. │ └─... %>% ...
  7. ├─global extract_tag(...)
  8. │ └─... %>% ...
  9. ├─dplyr::mutate(...)
 10. ├─dplyr::mutate(...)
 11. ├─global extract_tag(...)
 12. │ └─... %>% ...
 13. ├─dplyr::mutate(...)
 14. ├─dplyr::mutate(...)
 15. ├─dplyr:::mutate.data.frame(...)
 16. │ └─dplyr:::mutate_cols(.data, dplyr_quosures(...), caller_env = caller_env())
 17. │   ├─base::withCallingHandlers(...)
 18. │   └─mask$eval_all_mutate(quo)
 19. ├─purrr::pmap(...)
 20. │ └─.f(...)
 21. │   └─base::stop("More than one tag detected for: ", full_name)
 22. └─base::.handleSimpleError(...)
 23.   └─dplyr (local) h(simpleError(msg, call))
 24.     └─rlang::abort(...)
There were 50 or more warnings (use warnings() to see the first 50)
Execution halted
```

**Comment by maneesha** [comment]
@zkamvar  I believe we can close this - can you confirm?

**Comment by zkamvar** [comment]
Yes, this can be closed.
